services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - "/mnt/z/Library/Películas:/films"
      - "/mnt/z/Library/Series:/series"
    restart: "unless-stopped"
volumes:
  jellyfin-config:
    driver: local
  jellyfin-cache:
    driver: local
      
