services:
  jellyfin:
    build: .
    container_name: jellyfin
    depends_on:
      - tailscale
    network_mode: "service:tailscale"
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - "${NAS_MOUNT_POINT}:/media"
    environment:
      - NAS_IP=${NAS_IP}
      - NAS_SHARE=${NAS_SHARE}
      - NAS_USER=${NAS_USER}
      - NAS_PASSWORD=${NAS_PASSWORD}
      - NAS_MOUNT_POINT=${NAS_MOUNT_POINT}
      - JELLYFIN_PublishedServerUrl=http://alex-jellyfin.com
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    privileged: true
    expose: # Solo para poder acceder al jellyfin
      - "8096"
    ports: # Solo para poder acceder al jellyfin
      - "8096:8096"
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - /var/lib/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped

volumes:
  jellyfin-config:
    driver: local
  jellyfin-cache:
    driver: local
